### ISSUE TITLE
miniz on iOS device

### ISSUE THREAD

**Issue by duongbadu** [official-pikafish/Pikafish#12]
miniz (extract pikafish.nnue file) does not work when building for iOS device.

**Comment by PikaCat-OuO** [comment]
Any error message when building? Could you please provide a detailed screenshot of what's happening when building the binary on iOS?

**Comment by duongbadu** [comment]
+ zip is NULL in this line of code:
    struct zip_t *zip = zip_open(fpath.c_str(), 0, 'r');
+ method name: std::stringstream read_zipped_nnue(const std::string& fpath)
+ file: misc.cpp

info string ERROR: The network file /var/containers/Bundle/Application/*********-57F3-4167-B2DE-**************/ChineseChess172-mobile.app/books/pikafish.nnue was not loaded successfully.

**Comment by duongbadu** [comment]
I see that Stockfish use: incbin library to embed the NNUE file. Can we use incbin in Pikafish?

**Comment by Warm-rain** [comment]
You need to specify the nnue path with the command.
eg:setoption name EvalFile value /bin/pikafish.nnue

**Comment by duongbadu** [comment]
> You need to specify the nnue path with the command. eg:setoption name EvalFile value /bin/pikafish.nnue

already set in ucioption.cpp file:
  auto nnuePath = FileUtils::getInstance()->fullPathForFilename("pikafish.nnue");
o["EvalFile"]              << Option(nnuePath.c_str(), on_eval_file);

**Comment by PikaCat-OuO** [comment]
I believe chessroad-lite(https://github.com/hezhaoyun/chessroad-lite) have successfully build it. You can ask the author for help.

**Comment by lwfnz** [comment]
This is not an issue, so this topic should be closed.

**Comment by PikaCat-OuO** [comment]
Since it has been here for more than a year. I'll mark this as stale now.
