### ISSUE TITLE
有什么推荐的GUI软件配合使用吗?

### ISSUE THREAD

**Issue by timepp** [official-pikafish/Pikafish#25]
### Describe the issue

网上找了一圈都没有好用的

### Expected behavior

网上找了一圈都没有好用的

### Steps to reproduce

网上找了一圈都没有好用的

### Operating system

Windows

### Pikafish version

2022

**Comment by skystarspython** [comment]
鲨鱼象棋免费版可以试试

**Comment by timepp** [comment]
找到了, 鹏飞挺好用的.

**Comment by skarl-api** [comment]
巧夺天工象棋 QQ群：649544159 也挺好用的 @timepp
