### ISSUE TITLE
Variant Fishtest login pass code

### ISSUE THREAD

**Issue by studentbotnet** [official-pikafish/Pikafish#26]
### Describe the issue

Variant Fishtest login pass code

### Expected behavior

Variant Fishtest login pass code

### Steps to reproduce

Variant Fishtest login pass code

### Anything else?

Variant Fishtest login pass code

### Operating system

All

### Pikafish version

Pikafish

**Comment by studentbotnet** [comment]
http://test.pikafish.org

**Comment by PikaCat-OuO** [comment]
see https://github.com/official-pikafish/Pikafish/issues/8
thanks again, but we are currently not planning to open that publicly.
