### ISSUE TITLE
Perpetual chase: Black Cannon chases White Rook

### ISSUE THREAD

**Issue by nguyenpham** [official-pikafish/Pikafish#28]
### Describe the issue

Black Cannon chases White Rook

### Expected behavior

No chase

### Steps to reproduce

[Event "The best"]
[Site "My computer AMD"]
[Date "2023.01.30"]
[Time "15:25:09"]
[Round "*"]
[White "SA Chess 1.6"]
[Black "Pikafish 2022-10-22"]
[Result "1-0"]
[Termination "perpetual chase"]
[ECO "B04"]
[Opening "Central Cannon vs. Right 3 Step Tiger Counter"]
[TimeControl "40/300+1"]
[PlyCount "36"]
[Variant "xiangqi"]

1.Che2 Hc7 2.Hg2 Ca7
3.Cbd2 {B04: Central Cannon vs. Right 3 Step Tiger Counter}  Rb9 4.Hc2 Hg7
5.c4 g5 6.Rh0 Rh9
7.Rh6 Ci7 8.Rg6 Ci8
9.Ra2 Afe8 10.Rb2 Rxb2
11.Cxb2 Cg8 12.Rf6 Ege7
13.Rf8 Ca8 14.Cb8 Ad7
15.Cb3 A9e8 16.Cb8 Ad9
17.Cb3 A9e8 18.Cb8 Ad9
 1-0

### Operating system

All

### Pikafish version

Pikafish 2022-10-22

**Comment by PikaCat-OuO** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/73384062/215405115-2689639f-f007-450e-844c-e80ac437ef1a.png">
I think both sides are chasing here, red is chasing black cannon on g8.
Also, maybe you can use Pikafish 2022-12-26. There is a minor rule bug fix after Pikafish 2022-10-22.
