### ISSUE TITLE
eval command error

### ISSUE THREAD

**Issue by GundamDyname** [official-pikafish/Pikafish#38]
### Describe the issue

uci
id name Pikafish 2023-04-08
id author the Pikafish developers (see AUTHORS file)

option name Debug Log File type string default
option name Threads type spin default 1 min 1 max 1024
option name Hash type spin default 16 min 1 max 33554432
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 10 min 0 max 5000
option name Slow Mover type spin default 100 min 10 max 1000
option name nodestime type spin default 0 min 0 max 10000
option name Sixty Move Rule type check default true
option name Mate Threat Depth type spin default 1 min 0 max 10
option name Repetition Fold type combo default TwoFold var TwoFold var RootThreeFold var ThreeFold
option name Repetition Rule type combo default AsianRule var AsianRule var ChineseRule var SkyRule
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 1350 min 1350 max 2850
option name UCI_WDLCentipawn type check default true
option name UCI_ShowWDL type check default false
option name EvalFile type string default pikafish.nnue
uciok
eavl
Unknown command: 'eavl'. Type help for more information.

### Expected behavior

According to the wiki it should show the position score

### Steps to reproduce

eavl
Unknown command: 'eavl'. Type help for more information.

### Anything else?

eavl
Unknown command: 'eavl'. Type help for more information.

### Operating system

All

### Pikafish version

 Pikafish 2023-04-08

**Comment by PikaCat-OuO** [comment]
You need to type `eval` instead of `eavl`, typo issue.
