### ISSUE TITLE
no support for xboard 4.9 in linux

### ISSUE THREAD

**Issue by ntos1978** [official-pikafish/Pikafish#40]
### Describe the issue

I tried Pikafish.2023-02-16 on xboard 4.9.1 on ubuntu 20.04 and there is this error: variant xiangqi not supported by Pikafish dev 2023-02-16.
What a pity! 
Why stop supporting linux? What is the last version that supports xboard?

Thank you. 

### Expected behavior

latest version support for xboard.

### Steps to reproduce

xboard -variant xiangqi -ubt true -lbtf /usr/share/games/xboard/themes/textures/xqboard-9x10.png  -dbtf /usr/share/games/xboard/themes/textures/xqboard-9x10.png -pid /usr/share/games/xboard/themes/xiangqi  -trueColors true -overrideLineGap 0 -fcp /home/name/Downloads/Pikafish.2023-02-16/linux/pikafish-modern -fUCI 

### Operating system

Linux

### Pikafish version

Pikafish 2023-02-16

**Comment by PikaCat-OuO** [comment]
No, only UCI protocol is supported. You can try that on linux with liground GUI: https://github.com/mtaktikos/Pikafish/releases
If you really want to use xboard, consider using fairy-stockfish.

**Comment by hungpt-a8e** [comment]
I wrote a guide on how to use Pikafish with Xboard [here](https://github.com/official-pikafish/Pikafish/discussions/43), you can check out if you are interested.

**Comment by dlorre** [comment]
It's funny because I've started my Chess GUI because XBoard was over 30 years old and I thought it was time modernize this stuff.
