### ISSUE TITLE
pikafish.nnue无法使用

### ISSUE THREAD

**Issue by zhandoushu** [official-pikafish/Pikafish#42]
### Describe the issue

我下载的2023-03-05官方版release的zip和code，提取的zip里的nnue，code编译好后，bench解析不了nnue文件，查了下version与size都对不上，头文件解析错误

### Expected behavior

是我不会用nnue，还是没有找到正确的nnue文件，与code对应在哪里找呢

### Steps to reproduce

.。。

### Operating system

Windows

### Pikafish version

Pikafish 2023-03-05

**Comment by PikaCat-OuO** [comment]
这里面的nnue需要使用最新的master代码进行解析

**Comment by zhandoushu** [comment]
试了，没卵用，不匹配

**Comment by zhandoushu** [comment]
![11](https://github.com/official-pikafish/Pikafish/assets/125735391/9005fb00-04b8-4513-b20e-e16bd35e4119)
![22](https://github.com/official-pikafish/Pikafish/assets/125735391/aa61b735-a34f-4c72-a329-bba8a0b3d68d)

**Comment by PikaCat-OuO** [comment]
不可能的，现在的master分支上的每一个提交所对应的github ci/cd(github action)都是下载305压缩包里面的权重来跑bench。
如果使用vs编译的话，估计是vs对mini zip支持不行，你把pikafish.nnue改名成.zip文件，解压原始的nnue进行加载

**Comment by PikaCat-OuO** [comment]
垃圾vs

**Comment by zhandoushu** [comment]
按照你说的吧.nnue改为.zip,解压得到新的nnue文件，然后就能正常识别了，感谢！

**Comment by jyxxf** [comment]
NNUE文件怎么下载，现在压缩包中好像没有这个文件？

**Comment by zhandoushu** [comment]
在github域名后加上/Realse



---- 回复的原邮件 ----
| 发件人 | Xiaofan ***@***.***> |
| 日期 | 2024年01月18日 22:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [official-pikafish/Pikafish] pikafish.nnue无法使用 (Issue #42) |

NNUE文件怎么下载，现在压缩包中好像没有这个文件？

**Comment by zhandoushu** [comment]
或者用new bing搜pikafish realse



---- 回复的原邮件 ----
| 发件人 | Xiaofan ***@***.***> |
| 日期 | 2024年01月18日 22:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [official-pikafish/Pikafish] pikafish.nnue无法使用 (Issue #42) |

NNUE文件怎么下载，现在压缩包中好像没有这个文件？

**Comment by jyxxf** [comment]
> 在github域名后加上/Realse
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Xiaofan ***@***.***> | | 日期 | 2024年01月18日 22:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [official-pikafish/Pikafish] pikafish.nnue无法使用 (Issue #42) | NNUE文件怎么下载，现在压缩包中好像没有这个文件？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

感谢回复，不过应该是https://github.com/official-pikafish/Pikafish/releases 里面的那个30M的7z压缩包，或者是https://github.com/official-pikafish/Networks/releases/download/master-net/pikafish.nnue

**Comment by zhandoushu** [comment]
电脑不在身边，只记得了个大概，感谢指正



---- 回复的原邮件 ----
| 发件人 | Xiaofan ***@***.***> |
| 日期 | 2024年01月18日 23:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [official-pikafish/Pikafish] pikafish.nnue无法使用 (Issue #42) |

在github域名后加上/Realse
…
---- 回复的原邮件 ---- | 发件人 | Xiaofan @.> | | 日期 | 2024年01月18日 22:55 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [official-pikafish/Pikafish] pikafish.nnue无法使用 (Issue #42) | NNUE文件怎么下载，现在压缩包中好像没有这个文件？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

感谢回复，不过应该是https://github.com/official-pikafish/Pikafish/releases 里面的那个30M的7z压缩包，或者是https://github.com/official-pikafish/Networks/releases/download/master-net/pikafish.nnue
