### ISSUE TITLE
Android target SDK > 28 can no longer execute binaries in the data directory.

### ISSUE THREAD

**Issue by myisduy** [official-pikafish/Pikafish#49]
### Describe the issue

From android 10 version, we cannot execute binary file without root permission.  If they set targetSDK = 28, they cannot be released on the play store.

### Expected behavior

Any method that integrates the engine

### Steps to reproduce

public class Engine {
    public Engine(File engineFile) {
		String command = engineFile.getAbsolutePath();
		try {
			Process process = Runtime.getRuntime().exec(command);
		

			
			InputStream inputStream = process.getInputStream();
			BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

			
			String line;
			while ((line = reader.readLine()) != null) {
			
				Log.i("enginechess", line);
			}

			
			int exitCode = process.waitFor();
			Log.i("enginechess", "Exit code: " + exitCode);
		} catch (IOException | InterruptedException e) {
			e.printStackTrace();
		}
}

### Operating system

Android

### Pikafish version

Pikafish 2023-03-05

**Comment by PikaCat-OuO** [comment]
Ask this issue in the https://github.com/official-stockfish/Stockfish repo and see if there are any actions that need to be done.

**Comment by Liberations** [comment]
1.change name to libpikafish.so . move to project app/src/main/jniLibs/arm64-v8a
2.pikafish.nnue to assets/pikafish.nnue
`
        String apkFilePath = getPackageCodePath();

        // 推断lib目录路径
        LIB_PATH = apkFilePath.substring(0, apkFilePath.lastIndexOf("/")) + "/lib/arm64";
        File cacheDir = getCacheDir();
        String outputFilePath = cacheDir.getAbsolutePath() + File.separator + "pikafish.nnue";
        ENGIN_PATH = outputFilePath;
        Log.d(TAG, "LIB_PATH: " + LIB_PATH);
        Log.d(TAG, "ENGIN_PATH: " + ENGIN_PATH);
`
3.
Runtime.getRuntime().exec(LIB_PATH + "/libpikafish.so")
