### ISSUE TITLE
xiangqiai.com 无法访问

### ISSUE THREAD

**Issue by suniique** [official-pikafish/Pikafish#54]
### Describe the issue

开发者您好，我经常使用Pikafish的在线版 http://www.xiangqiai.com/ 网站，非常便利。但近期该网站似乎无法访问，想询问一下~
感谢！

### Error message

‘DNS_PROBE_FINISHED_NXDOMAIN’

### Operating system

All

### Pikafish version

web

**Comment by Vincentzyx** [comment]
你好，为了更快的访问速度，xiangqiai.com正在进行域名备案，备案期间需要关站，备案结束后才会恢复访问。再次之前，你可以先使用镜像站 https://ai.pikafish.org

**Comment by suniique** [comment]
非常感谢回复！
