### ISSUE TITLE
linux 下编译出错

### ISSUE THREAD

**Issue by leatherking** [official-pikafish/Pikafish#64]
### Describe the issue

我在ubuntu 20.04 和 22.04里面编译src/，按照官方给的样例` make -j profile-build ARCH=x86-64-avx2`，没有编译成功。
报错信息为 `‘Stockfish::SquareBB’ was not declared ‘constexpr’`
![image](https://github.com/official-pikafish/Pikafish/assets/44730902/0ed8370f-3406-4561-92d6-0a320c5ff66e)

### Expected behavior

编译

### Steps to reproduce

`cd src/`
`make -j profile-build ARCH=x86-64-avx2`

### Operating system

Linux

### Pikafish version

最新仓库

**Comment by PikaCat-OuO** [comment]
fixed
