### ISSUE TITLE
Failed to load NNUE file on iOS

### ISSUE THREAD

**Issue by suidongyang** [official-pikafish/Pikafish#80]
### Describe the issue

我使用如下命令加载 nnue 文件：

setoption name EvalFile value /private/var/containers/Bundle/Application/AACAD639-3EF0-4BAC-B68F-5B1E8C4DBF40/Chess.app/pikafish.nnue

报错如下：

info string ERROR: Network evaluation parameters compatible with the engine must be available.
info string ERROR: The network file /private/var/containers/Bundle/Application/AACAD639-3EF0-4BAC-B68F-5B1E8C4DBF40/Chess.app/pikafish.nnue was not loaded successfully.
info string ERROR: The UCI option EvalFile might need to specify the full path, including the directory name, to the network file.
info string ERROR: The engine will be terminated now.

wiki 中提到要使用全路径，为什么不行呢

### Expected behavior

成功加载 nnue

### Steps to reproduce

On iOS Device:
uci\n
setoption name Threads value 6\n
setoption name EvalFile value /private/var/containers/Bundle/Application/AACAD639-3EF0-4BAC-B68F-5B1E8C4DBF40/Chess.app/pikafish.nnue\n

### Operating system

Other or N/A

### Pikafish version

Pikafish dev 2024-09-23

**Comment by suidongyang** [comment]
换用最新的release版后问题解决了

**Comment by skystarspython** [comment]
NNUE架构和引擎架构不匹配，皮卡鱼最近更换了NNUE架构。
